# Generated by Django 4.1.7 on 2023-06-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_contract', models.CharField(default='20/05/2023', max_length=120)),
                ('contract_number', models.CharField(default='1065732', max_length=120)),
                ('usage_type', models.CharField(max_length=120)),
                ('contract_starting_date', models.CharField(default='20/05/2024', max_length=120)),
                ('contract_expiry_date', models.CharField(default='19/05/2024', max_length=120)),
                ('monthly_rent', models.CharField(blank=True, max_length=120, null=True)),
                ('contract_fees', models.CharField(blank=True, max_length=120, null=True)),
                ('rented_loom', models.CharField(blank=True, max_length=120, null=True)),
                ('name', models.CharField(blank=True, default='شركة الدعم التنمية للاستثمار', max_length=120, null=True)),
                ('name_2', models.CharField(blank=True, max_length=120, null=True)),
                ('khaif_no', models.CharField(blank=True, max_length=120, null=True)),
                ('card_no', models.CharField(default='6491949', max_length=120)),
                ('commercial_register', models.CharField(default='1396496', max_length=120)),
                ('nationality', models.CharField(blank=True, max_length=120, null=True)),
                ('state', models.CharField(blank=True, max_length=120, null=True)),
                ('street', models.CharField(blank=True, max_length=120, null=True)),
                ('almatqatu', models.CharField(default='الصناعيات الجديدة', max_length=120)),
                ('electricity_account_number', models.CharField(blank=True, max_length=120, null=True)),
                ('property_type', models.CharField(blank=True, max_length=120, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=120, null=True)),
                ('vichle_mechanic_repair', models.CharField(blank=True, max_length=120, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='media/qr_code')),
            ],
        ),
    ]
