# Generated by Django 4.1.7 on 2023-06-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrecord',
            name='contract_fees',
            field=models.CharField(blank=True, default='366', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='addrecord',
            name='electricity_account_number',
            field=models.CharField(blank=True, default='2862682', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='addrecord',
            name='nationality',
            field=models.CharField(blank=True, default='عمان', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='addrecord',
            name='phone_number',
            field=models.CharField(blank=True, default='00000000', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='addrecord',
            name='vichle_mechanic_repair',
            field=models.CharField(blank=True, default='452002', max_length=120, null=True),
        ),
    ]
