# Generated by Django 4.1.7 on 2023-06-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_alter_addrecord_usage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrecord',
            name='field_type',
            field=models.CharField(blank=True, default='صلالة', max_length=120, null=True),
        ),
    ]
