# Generated by Django 4.1.7 on 2023-06-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_addrecord_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrecord',
            name='phone_number2',
            field=models.CharField(blank=True, default='00000000', max_length=120, null=True),
        ),
    ]
