# Generated by Django 4.1.7 on 2023-06-09 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_addrecord_phone_number2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrecord',
            name='khaif_no',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='addrecord',
            name='monthly_rent',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='addrecord',
            name='name_2',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='addrecord',
            name='property_type',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='addrecord',
            name='rented_loom',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='addrecord',
            name='state',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='addrecord',
            name='street',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
    ]
