# Generated by Django 4.1.7 on 2023-06-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0007_alter_addrecord_khaif_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrecord',
            name='raqmul_qareebi',
            field=models.CharField(blank=True, default='0', max_length=120, null=True),
        ),
    ]
