# Generated by Django 4.1.7 on 2023-06-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_addrecord_raqmul_qatga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrecord',
            name='name_2',
            field=models.CharField(blank=True, default='شركة ضواحي الريف للمشاريع المتقدمة ش ', max_length=120, null=True),
        ),
    ]
