# Generated by Django 4.1.7 on 2023-06-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0010_alter_addrecord_name_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrecord',
            name='name_2',
            field=models.CharField(blank=True, default='ؤسسة سحابة شمال الشرقي المتميز للتجارة والمقاولات', max_length=120, null=True),
        ),
    ]
