# Generated by Django 4.1.7 on 2023-06-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0012_alter_addrecord_name_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrecord',
            name='monthly_rent',
            field=models.CharField(blank=True, default='10', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='addrecord',
            name='rented_loom',
            field=models.CharField(blank=True, default='شرکة', max_length=120, null=True),
        ),
    ]
