# Generated by Django 4.1.7 on 2023-06-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_alter_addrecord_monthly_rent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrecord',
            name='rented_loom2',
            field=models.CharField(blank=True, default='شرکة', max_length=120, null=True),
        ),
    ]
