# Generated by Django 4.1.7 on 2023-06-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0014_addrecord_rented_loom2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrecord',
            name='commercial_register',
            field=models.CharField(blank=True, default='1396496', max_length=120, null=True),
        ),
    ]
