# Generated by Django 4.1.7 on 2023-06-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0017_alter_addrecord_khaif_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrecord',
            name='commercial_register2',
            field=models.CharField(blank=True, default='0000000', max_length=120, null=True),
        ),
    ]
