# Generated by Django 4.1.7 on 2023-06-11 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0018_alter_addrecord_commercial_register2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addrecord',
            old_name='commercial_register2',
            new_name='commercial_register_2',
        ),
    ]
