# Generated by Django 4.1.7 on 2023-09-03 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0019_rename_commercial_register2_addrecord_commercial_register_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrecord',
            name='plot_no',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='addrecord',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='addrecord',
            name='street',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
