# Generated by Django 4.1.7 on 2023-09-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0020_addrecord_plot_no_alter_addrecord_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addrecord',
            name='plot_no',
        ),
        migrations.AddField(
            model_name='addrecord',
            name='block',
            field=models.CharField(blank=True, default='ب', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='addrecord',
            name='street',
            field=models.CharField(blank=True, default='شارغ عام', max_length=120, null=True),
        ),
    ]
