# Generated by Django 4.1.7 on 2023-09-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0021_remove_addrecord_plot_no_addrecord_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrecord',
            name='profession2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
