# Generated by Django 4.1.7 on 2023-09-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0022_addrecord_profession2'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrecord',
            name='vichle_mechanic_repair2',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
