# Generated by Django 4.1.7 on 2023-09-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0023_addrecord_vichle_mechanic_repair2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrecord',
            name='name',
            field=models.CharField(blank=True, default=' مجدى بن مستهيل بن منجور جعبوب ', max_length=120, null=True),
        ),
    ]
