# Generated by Django 4.1.7 on 2023-09-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0024_alter_addrecord_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrecord',
            name='card_no',
            field=models.CharField(default='5413313', max_length=120),
        ),
        migrations.AlterField(
            model_name='addrecord',
            name='phone_number',
            field=models.CharField(blank=True, default='72582037', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='addrecord',
            name='phone_number2',
            field=models.CharField(blank=True, default='92792776', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='addrecord',
            name='usage_type',
            field=models.CharField(blank=True, default=' تجاري ', max_length=120, null=True),
        ),
    ]
