# Generated by Django 4.1.7 on 2023-09-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0025_alter_addrecord_card_no_alter_addrecord_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addrecord',
            name='khaif_no',
            field=models.CharField(blank=True, default='1341270', max_length=120, null=True),
        ),
    ]
